//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoachoSLN.Resource.prospectos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class form {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal form() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoachoSLN.Resource.prospectos.form", typeof(form).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string apellido1 {
            get {
                return ResourceManager.GetString("apellido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido 2.
        /// </summary>
        public static string apellido2 {
            get {
                return ResourceManager.GetString("apellido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificacion.
        /// </summary>
        public static string calificacion {
            get {
                return ResourceManager.GetString("calificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle.
        /// </summary>
        public static string calle {
            get {
                return ResourceManager.GetString("calle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string celular {
            get {
                return ResourceManager.GetString("celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string ciudad {
            get {
                return ResourceManager.GetString("ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Postal.
        /// </summary>
        public static string codigopostal {
            get {
                return ResourceManager.GetString("codigopostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string compania {
            get {
                return ResourceManager.GetString("compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertido a Cliente.
        /// </summary>
        public static string convertido {
            get {
                return ResourceManager.GetString("convertido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string estatus {
            get {
                return ResourceManager.GetString("estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dueño.
        /// </summary>
        public static string iddueño {
            get {
                return ResourceManager.GetString("iddueño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industria.
        /// </summary>
        public static string idindustria {
            get {
                return ResourceManager.GetString("idindustria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        public static string idorigen {
            get {
                return ResourceManager.GetString("idorigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos.
        /// </summary>
        public static string ingresos {
            get {
                return ResourceManager.GetString("ingresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° de empleados.
        /// </summary>
        public static string numempleado {
            get {
                return ResourceManager.GetString("numempleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina.
        /// </summary>
        public static string pagina {
            get {
                return ResourceManager.GetString("pagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string skype {
            get {
                return ResourceManager.GetString("skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono Extra.
        /// </summary>
        public static string telefono2 {
            get {
                return ResourceManager.GetString("telefono2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        public static string textoextra {
            get {
                return ResourceManager.GetString("textoextra", resourceCulture);
            }
        }
    }
}
